name: publish

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ "zero" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "zero" ]

env:
  REGISTRY: ghcr.io
  USER: ${{ github.actor }}
  PASS: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }} 
      - name: Build and publish base
        run: |
          make IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} base
          docker publish ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Build and publish multilib
        run: |
          make IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} multilib
          docker publish ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:multilib

